// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA30WvUw_amGUiwBdNwkTPv6tU8Fbgzb64',
    appId: '1:610542394780:web:9e1014918c5b864de7bc59',
    messagingSenderId: '610542394780',
    projectId: 'crudflutterfire-75947',
    authDomain: 'crudflutterfire-75947.firebaseapp.com',
    storageBucket: 'crudflutterfire-75947.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7myLslTle1-v8EcOZRQTAZ09gPwmEdSE',
    appId: '1:610542394780:android:67962aa02ed4a9ede7bc59',
    messagingSenderId: '610542394780',
    projectId: 'crudflutterfire-75947',
    storageBucket: 'crudflutterfire-75947.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcXMDgxjom76LrkCuQzAIcpQsct9DEO0',
    appId: '1:610542394780:ios:870cf950953dd13be7bc59',
    messagingSenderId: '610542394780',
    projectId: 'crudflutterfire-75947',
    storageBucket: 'crudflutterfire-75947.appspot.com',
    iosClientId: '610542394780-1idc4fj3gdtgm7fl1t6j5ocl8vttrdl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudflutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcXMDgxjom76LrkCuQzAIcpQsct9DEO0',
    appId: '1:610542394780:ios:870cf950953dd13be7bc59',
    messagingSenderId: '610542394780',
    projectId: 'crudflutterfire-75947',
    storageBucket: 'crudflutterfire-75947.appspot.com',
    iosClientId: '610542394780-1idc4fj3gdtgm7fl1t6j5ocl8vttrdl5.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudflutterfire',
  );
}
